### ISSUE TITLE
Find new owner

### ISSUE THREAD

**Issue by dylanlingelbach** [markitx/dynamo-backup-to-s3#51]
I have been unable to get write access to this repo and my time to work on this project is very small. I'd like to see if we can find a new owner to help maintain this. 

I think the process should look like:
- Fork this project to new org/owner
- Comment on existing PRs to get them to move their PR to forked project
- I move NPM package to new org/owner

Assigning a few people who have contributed in the past to see if anyone is able/willing to own.

**Comment by dylanlingelbach** [comment]
Arg, I can't even assign people. @ mentioning people here.

@sdesalas @adambiggs @apoorvmalhotra @mousavian @zezke @mlimaloureiro

**Comment by cg-cnu** [comment]
@dylanlingelbach I am actively using this package and would like to see it find a new home. I can make a couple of prs once the owner is decided. Thanks for bringing this up :)

**Comment by mousavian** [comment]
@dylanlingelbach Thank you very much for this;
I have already forked and applied my changes since I was blocked by that.

Here's my changes compare to this repo:
https://github.com/markitx/dynamo-backup-to-s3/compare/master...mousavian:master
https://www.npmjs.com/package/dr-dynamo

I will not have any problem by removing my fork and contributing to the new repo or adding people to dr-dynamo as contributor for further development.

**Comment by dylanlingelbach** [comment]
I was able to get access to this repo finally. I'll try to find some time to review/merge PRs this weekend. Would still like to find someone else to help own this.

Closing this issue for now, please comment if you are willing/able to help own.

**Comment by sdesalas** [comment]
Interested
